import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ожидайте",
  description: "Generated by create next app",
};

export default async function ServiceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {children}
    </section>
  );
}
