import Sidebar from "@/components/Sidebar";
import { getUser } from "@/utils/api/auth";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Товары",
  description: "Generated by create next app",
};


export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser()

  return (
    <section>
      <Sidebar user={user} />

      <main className="pl-20 md:pl-64 pr-6 md:pr-16 pt-10 pb-24">
        {children}
      </main>
    </section>
  );
}
