import logo from '@/../public/images/snr-logo.svg';
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Товары",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const status = true

  return (
    <section>
      {
        status ?
          <>
            <Sidebar />

            <main className="pl-64 pr-16 pt-10 pb-24">
              {children}
            </main>
          </>
          :
          <ApprovementWaiting />
      }
    </section>
  );
}

function ApprovementWaiting() {
  return (
    <div className="h-screen w-screen grid place-items-center">
      <div>
        <Image
          src={logo}
          alt="S&R logo"
          className='w-16'
        />
      </div>

      <div className=" text-center grid place-items-center w-full">
        <div className="text-2xl font-semibold">Ожидайте добавления...</div>
        <div className="w-full md:w-1/3">Доступ к личному кабинету компании отсутствует. Попросите добавить вас, указав ваш номер телефона.</div>
      </div>

      <div className=" font-medium"><span className="text-gray-normal font-normal">Поддержка:</span> +998 99 299 32 33</div>
    </div>
  )
}
