import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { verifyToken } from "@/utils/auth";
import Sidebar from "@/components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await verifyToken();

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-light-0`}>
        {isAuthenticated && <Sidebar />}

        <main className="pl-64 pr-16 pt-10 pb-24">
          {children}
        </main>
      </body>
    </html>
  );
}
