import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { verifyToken } from "@/utils/auth";
import Sidebar from "@/components/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await verifyToken();

  return (
    <html lang="en">
      <body className={inter.className}>
        {isAuthenticated && <Sidebar />}

        <main className="px-3.5 pt-10 pb-24 md:px-16">
          {children}
        </main>
      </body>
    </html>
  );
}
